### ISSUE TITLE
개개인의 스마트폰으로 웹사이트 접속 시 출력될 양식이 일정하지 않게 표시되는 문제

### ISSUE THREAD

**Issue by tay97kim** [tay97kim/Opensource-Project#1]
크기가 서로 다르게 표시되거나 축소, 확대가 되고 있어서 서비스의 제공이 원활하지 않을 것으로 예상됨. 해결방법이 있는 사람은 의견 남겨주길 바람.

**Comment by eogus6512** [comment]
head 태그에 meta 태그를 삽입하여 사용자가 화면 크기를 움직이지 못하고 정해진 크기로 고정 시키는 코드를 입력한다
기존 코드 : <meta name="viewport" content = "width=device-width, initial-scale=1">
변경된 코드 : <meta name="viewport" content = "width=device-width, initial-scale=1, user-scalable=no">

**Comment by eogus6512** [comment]
head 태그에 있는 meta 태그에 모바일에서 웹 화면을 고정시켜 사용자가 화면 크기를 바꾸지 못하게 하는 코드를 입력한다.
기존 코드 : meta name="viewport" content="width=device-width, initial-scale=1
변경된 코드 : meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no

**Comment by tay97kim** [comment]
수정 후 현상이 없어져 해결되었기 때문에 이슈를 닫습니다.
