### ISSUE TITLE
캠이 실행후에 화면이 출력되어 구도가 변경되는 문제

### ISSUE THREAD

**Issue by tay97kim** [tay97kim/Opensource-Project#2]
캠 실행 이전에 틀을 표현해두고 실행하게되면 그 속에서 출력되도록 처리하면 될 것으로 보임. 해결방법이 있다면 의견을 남겨주길 바람.

**Comment by eogus6512** [comment]
boder로 실행되기 전에 카메라 박스를 미리 만들어두고 해당 태그 내부에 웹 캠 태그를 넣어 웹 캠을 실행할 경우 빈 박스 안에서 웹 캠이 실행될 수 있도록 만든다.
style type="text/css"
  .cam-box{width : 320px; height : 380px;  border : 1px solid; padding : 5px; margin : 10 10 10 10;}
  /style
div class="cam-box"
   div id = "webcam-container /div
   /div

**Comment by tay97kim** [comment]
수정 이후에 캠 실행 전에도 틀이 유지되어 문제가 해결되었으므로 이슈를 닫습니다.
