### ISSUE TITLE
웹캠으로 인물 확인 시 알림창을 닫고 난 다음 다시 알림창이 바로 뜨는 문제

### ISSUE THREAD

**Issue by tay97kim** [tay97kim/Opensource-Project#3]
알림창을 닫고 난 뒤에 딜레이를 줄 필요가 있어보이는데, 좋은 아이디어가 있다면 의견 남겨주길 바람.

**Comment by eogus6512** [comment]
처음 코드에 나와있던 predict()문과 loop()문을 합친다음 confirm문에서 true를 선택 시 원하는 기능이 시작 되도록 if 조건문을 걸어주었고 false를 선택 시 webCam을 재시작하여 loop문을 다시 실행하게 하였다.
		var result = confirm('******');
		if (result == true ){
			
		}
		else{
			webcam.update();
			window.requestAnimationFrame(loop);
		}

**Comment by tay97kim** [comment]
해당 코드 추가 후 문제를 해결하였으므로 이슈를 닫습니다.
