### ISSUE TITLE
JavaScript 코드에서 Python 스크립트를 실행하고 Web Server에 해당 결과값을 가져오는 것이 안됨

### ISSUE THREAD

**Issue by eogus6512** [tay97kim/Opensource-Project#4]
JavaScript 코드에서 Python 스크립트를 실행하는 코드와
Python 스크립트 실행 결과값을 Web Server에 출력하는 코드를 찾아 해결책을 제시해 주세요

**Comment by tay97kim** [comment]
HTML 파일에서 파이썬 실행값을 가져오지 못해 발생한 문제로, 
HTML 파일이 아닌 PHP 파일로 변경한 뒤 코드의 시작 부분에 

? //PHP코드로 꺽쇠(<)로 열고 작성해야 함
exec("cd /opt/lampp/htdocs/ai && python3 test.py", $out, $status);
$temp = $out[0]
? //PHP코드로 꺽쇠(>)로 닫아주어야  함

코드를 추가하고, 모델을 비교하는 각 코드에 [아래: 기존코드]

if(prediction[0].className == "BaekDH" && prediction[0].probability.toFixed(2) >= 0.95) {
            labelContainer.childNodes[0].innerHTML = "BaekDH"
		var result = confirm('baek?');
		if (result == true ){
			//참일 때 불러올 데이터 코드
		}
		else{
			webcam.update();
			window.requestAnimationFrame(loop);
		}
			
}

 PHP 형식을 위한 labelContainer와 var test = '<?= $temp?>'코드를 추가하여 [아래: 수정코드]

if(prediction[0].className == "BaekDH" && prediction[0].probability.toFixed(2) >= 0.95) {
            labelContainer.childNodes[0].innerHTML = "BaekDH" //
		var result = confirm('baek?');
		if (result == true ){
		var test = '<?= $temp?>'
		 labelContainer.childNodes[1].innerHTML = test
		}
		else{
			webcam.update();
			window.requestAnimationFrame(loop);
		}
			
}

의 형태로 모델 비교 코드를 수정해주게 되면 파이썬 스크립트 실행 결과값을 불러올 수 있다.
