### ISSUE TITLE
php파일을 파이썬에서 실행 시 결과 값이 html로 전달되지 않는 문제.

### ISSUE THREAD

**Issue by tay97kim** [tay97kim/Opensource-Project#5]
서비스를 구현하기 위해선 파이썬에서 실행된 결과 값이 html 상으로 전달되어야만 하는데, 해결하기 위한 방법에 대해 의견을 남겨주세요.

**Comment by phyyyhy** [comment]
Python 코드 추가
file = open('file path', 'w')
file.write(attence_sentence)
file.close

php 코드 수정
exec("cd file path", $out, $return);

php를 사용하여 파이썬 스크립트를 실행하고 실행된 결과값을 텍스트 파일로 저장 후 js에서 파일을 불러오는 방식

**Comment by tay97kim** [comment]
의견에 대한 코드로 테스트 해본 결과 값이 전달되는 것을 확인했으므로 이슈를 닫습니다.
