### ISSUE TITLE
alert와 confirm문에는 버튼이 몇개 없다 해결책을 찾아야한다

### ISSUE THREAD

**Issue by phyyyhy** [tay97kim/Opensource-Project#6]
여러 버튼을 사용할 수 있는 함수를 찾았으면 한다.

**Comment by eogus6512** [comment]
기존 alert나 comfirm은 지정된 디자인이 있어서 불가하다 하지만 function을 사용하여 경고창을 디자인해서 만들어 해결이 가능하다
function btn() {
$('#message') dialog({
modal:true,
buttons:{
"출석정보" : function() {
readTextFile(file)
}
"출석정보" : function() {
readTextFile(file)
}
"출석정보" : function() {
readTextFile(file)
}
}
