### ISSUE TITLE
php로 파이썬을 실행한 후 파일에 저장해서 파일에 대한 내용을 불러와야 하는데 불러와지지 않는다

### ISSUE THREAD

**Issue by phyyyhy** [tay97kim/Opensource-Project#7]
해결책을 찾아주기바란다

**Comment by eogus6512** [comment]
function readTextFile(file)
{
    var rawFile = new XMLHttpRequest();
    rawFile.open("GET", file, false);
    rawFile.onreadystatechange = function ()
    {
        if(rawFile.readyState === 4)
        {
            if(rawFile.status === 200 || rawFile.status == 0)
            {
                var allText = rawFile.responseText;
                alert(allText);
            }
        }
    }
    rawFile.send(null);
}

해당 코드를 사용하는데 리눅스로 파일을 관리하기때문에 파일 권한을 줘야하고 그리고 서버를 열린 상태에서만 가능하기 때문에 web in browser 등에서 확인하기에는 힘들다

**Comment by phyyyhy** [comment]
좋은 답변이 되었습니다
